#!/usr/bin/env python3
"""Check reviewed source contents and explicit publication archive membership.

The checked-in manifest is a review decision, never regenerated by CI. Editing
it requires reviewing the changed files for publication, including test data.
This gate supplements human review; it does not certify older Git history.
"""
import argparse
import ast
import hashlib
import io
import json
import pathlib
import re
import stat
import subprocess
import tarfile
import zipfile

ROOT = pathlib.Path(__file__).resolve().parents[2]
MANIFEST = 'scripts/release/public-source.json'
BUNDLE_FILES = {'hollis', 'hollis-native', 'hollis-bridges.zip', 'LICENSE', 'manifest.json'}
BRIDGE_FILES = {'AFM Bridge - Cloud.shortcut', 'AFM Bridge - Cloud Pro.shortcut', 'AFM Bridge - On-Device.shortcut', 'AFM Bridge - ChatGPT.shortcut', 'Hollis Image - Reference Input v2.shortcut'}
PRIVATE_PREFIXES = ('docs/dev/', 'assets/brand/', '.git/', '.claude/', '.venv/',
                    'scripts/live-suite/', 'scripts/image-suite/', 'plugins/hollis/examples/recorded/')
PRIVATE_NAMES = {'macos-26-compat.md', 'tool-protocol-26A5425a.md',
                 'v0.2.0-live-validation-2026-09-03.json', 'advanced-cli-test-2026-09-01.md',
                 'v0.3.2-validation.json', 'plugin-review-closure.md', 'recorded-demo.md',
                 'host_demo.py', 'live_validate.py', 'live_test.go', 'image_live_test.go'}
MAX_MEMBER = 128 * 1024 * 1024
MAX_ARCHIVE = 512 * 1024 * 1024
# Only the named fictional privacy-test paths are exempt, never entire tests.
PATTERNS = {
    'personal home path': re.compile(b'/' + rb'Users/(?!private/|example/|fixture/|runner/|test/)[A-Za-z0-9_.-]+/'),
    'private task link': re.compile(b'codex:' + b'//threads/'),
    'credential value': re.compile(rb'(?:gh[pousr]_[A-Za-z0-9]{20,}|github_pat_[A-Za-z0-9_]{30,}|sk-(?:proj-)?[A-Za-z0-9_-]{24,}|AKIA[A-Z0-9]{16})'),
    'private key': re.compile(b'-----BEGIN ' + rb'(?:RSA |EC |OPENSSH )?PRIVATE KEY-----'),
}


def check_names(names, kind='source'):
    clean = []
    for name in names:
        path = pathlib.PurePosixPath(name)
        if path.is_absolute() or '..' in path.parts or '\\' in name:
            raise ValueError(f'Unsafe archive path: {name}')
        normalized = path.as_posix().rstrip('/')
        if normalized not in ('', '.'):
            clean.append(normalized)
    if kind in ('source', 'plugin') and clean and all('/' in n for n in clean):
        roots = {n.split('/')[0] for n in clean}
        if len(roots) == 1 and next(iter(roots)).startswith(('hollis-', 'kamenxrider-hollis-')):
            clean = [n.split('/', 1)[1] for n in clean]
    if len(clean) != len(set(clean)):
        raise ValueError('Duplicate archive member')
    for name in clean:
        parts = pathlib.PurePosixPath(name).parts
        if any(name == p.rstrip('/') or name.startswith(p) for p in PRIVATE_PREFIXES):
            raise ValueError(f'Private material in {kind}: {name}')
        if kind == 'source' and name.startswith('plugins/hollis/assets/runtime/'):
            raise ValueError(f'Bundled runtime in source: {name}')
        if any(p in PRIVATE_NAMES or p.endswith('-evidence.json') or p == '.env'
               or p.startswith('.env.') or p == '__pycache__' for p in parts):
            raise ValueError(f'Private or generated material in {kind}: {name}')
    if kind in ('bundle', 'bridges'):
        expected = BUNDLE_FILES if kind == 'bundle' else BRIDGE_FILES
        exact_members(clean, expected, kind)
    return clean


def exact_members(names, expected, kind):
    if set(names) != set(expected):
        raise ValueError(f'Unreviewed or missing {kind} files: {sorted(set(names) ^ set(expected))}')


def check_content(name, data):
    for rule, pattern in PATTERNS.items():
        if pattern.search(data):
            # Never include matched data in diagnostics.
            raise ValueError(f'Publication content rejected: {name} ({rule})')


def read_manifest(root=ROOT):
    data = json.loads((root / MANIFEST).read_bytes())
    if set(data) != {'schema_version', 'files'} or data['schema_version'] != 1:
        raise ValueError('Invalid public source manifest')
    files = data['files']
    if not isinstance(files, dict) or MANIFEST in files:
        raise ValueError('Invalid public source file list')
    check_names(files)
    if any(not isinstance(v, str) or not re.fullmatch('[0-9a-f]{64}', v) for v in files.values()):
        raise ValueError('Invalid reviewed content hash')
    return files


def check_source(contents, reviewed):
    exact_members(contents, set(reviewed) | {MANIFEST}, 'source')
    for name, data in contents.items():
        check_content(name, data)
        if name != MANIFEST and hashlib.sha256(data).hexdigest() != reviewed[name]:
            raise ValueError(f'Source content needs publication review: {name}')
    # The archive must carry the same manifest as the external review authority.
    if json.loads(contents[MANIFEST]) != {'schema_version': 1, 'files': reviewed}:
        raise ValueError('Source archive substituted its review manifest')


def archive_contents(path):
    result = {}
    total = 0

    def add(name, size, read):
        nonlocal total
        if name in result:
            raise ValueError(f'Duplicate archive member: {name}')
        total += size
        if size > MAX_MEMBER or total > MAX_ARCHIVE:
            raise ValueError('Archive exceeds inspection limits')
        result[name] = read()

    if zipfile.is_zipfile(path):
        if hasattr(path, 'seek'):
            path.seek(0)
        with zipfile.ZipFile(path) as archive:
            for member in archive.infolist():
                mode = stat.S_IFMT(member.external_attr >> 16)
                if mode not in (0, stat.S_IFREG, stat.S_IFDIR):
                    raise ValueError(f'Non-regular archive entry: {member.filename}')
                if not member.is_dir():
                    add(member.filename, member.file_size, lambda m=member: archive.read(m))
    else:
        if hasattr(path, 'seek'):
            path.seek(0)
        with tarfile.open(fileobj=path) if hasattr(path, 'read') else tarfile.open(path) as archive:
            for member in archive.getmembers():
                if not member.isfile() and not member.isdir():
                    raise ValueError(f'Non-regular archive entry: {member.name}')
                if member.isfile():
                    add(member.name, member.size, lambda m=member: archive.extractfile(m).read())
    return result


def archive_names(path):
    return list(archive_contents(path))


def plugin_files(root=ROOT):
    tree = ast.parse((root / 'scripts/plugin/package_plugin.py').read_text())
    names = next(ast.literal_eval(n.value) for n in tree.body if isinstance(n, ast.Assign)
                 and any(isinstance(t, ast.Name) and t.id == 'SOURCE_ALLOWLIST' for t in n.targets))
    return {'plugins/hollis/' + n for n in names} | {
        '.agents/plugins/marketplace.json', '.claude-plugin/marketplace.json',
        *('plugins/hollis/assets/runtime/' + n for n in (
            'hollis-darwin-arm64', 'hollis-native-darwin-arm64', 'hollis-bridges.zip', 'provenance.json')),
    }


def check_archive(path, kind, root=ROOT):
    contents = archive_contents(path)
    clean = check_names(contents, kind)
    contents = dict(zip(clean, contents.values()))
    if kind == 'source':
        check_source(contents, read_manifest(root))
    if kind == 'plugin':
        exact_members(contents, plugin_files(root), kind)
        reviewed = read_manifest(root)
        for name, data in contents.items():
            if name in reviewed and hashlib.sha256(data).hexdigest() != reviewed[name]:
                raise ValueError(f'Plugin source differs from reviewed content: {name}')
    for name, data in contents.items():
        check_content(name, data)
        if name.endswith('.zip'):
            if pathlib.PurePosixPath(name).name != 'hollis-bridges.zip':
                raise ValueError(f'Unexpected nested archive: {name}')
            check_archive(io.BytesIO(data), 'bridges', root)
    return contents


def check_release_dir(folder, kind, root=ROOT):
    if kind == 'plugin':
        version = json.loads((root / 'plugins/hollis/plugin.json').read_text())['version']
        stem = f'hollis-plugin-{version}'
        expected = {stem + ext for ext in ('.zip', '.sha256', '.runtime-provenance.json')}
    else:
        # Derive version from the bundle's declared version, not a user-selected glob.
        bundles = list(folder.glob('hollis-*-darwin-arm64.zip'))
        if len(bundles) != 1:
            raise ValueError('Expected one runtime bundle')
        data = check_archive(bundles[0], 'bundle', root)
        version = json.loads(data['manifest.json'])['version']
        if not re.fullmatch(r'\d+\.\d+\.\d+', version):
            raise ValueError('Invalid runtime version')
        expected = {'hollis-darwin-arm64', 'hollis-darwin-amd64', 'hollis-native-darwin-arm64',
                    'hollis-bridges.zip', f'hollis-{version}-darwin-arm64.zip', 'SHA256SUMS', 'hollis.spdx.json'}
    exact_members([p.name for p in folder.iterdir()], expected, 'release assets')
    for path in folder.iterdir():
        if path.is_symlink() or not path.is_file():
            raise ValueError(f'Unsafe release asset: {path.name}')
        check_content(path.name, path.read_bytes())
        if path.suffix == '.zip':
            check_archive(path, 'plugin' if kind == 'plugin' else
                          ('bridges' if path.name == 'hollis-bridges.zip' else 'bundle'), root)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument('--source', action='store_true')
    group.add_argument('--archive', type=pathlib.Path)
    group.add_argument('--release-dir', type=pathlib.Path)
    parser.add_argument('--kind', choices=['source', 'bundle', 'bridges', 'plugin'], default='source')
    args = parser.parse_args()
    if args.source:
        names = subprocess.check_output(['git', 'ls-files', '-z', '--cached', '--others', '--exclude-standard'], cwd=ROOT).decode().split('\0')
        names = check_names([n for n in names if n], 'source')
        contents = {}
        for name in names:
            path = ROOT / name
            if path.is_symlink() or not path.is_file():
                raise ValueError(f'Missing or unsafe source file: {name}')
            contents[name] = path.read_bytes()
        check_source(contents, read_manifest())
    elif args.archive:
        check_archive(args.archive, args.kind)
    else:
        check_release_dir(args.release_dir, args.kind)
    print('Publication privacy check passed.')


if __name__ == '__main__':
    main()
